language: node_js
node_js:
  - 4
  - 6

sudo: required
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

install:
  - yarn install
  - npm link ../create-elm-app

script: npm test

notifications:
  email:
    - eduard.kyvenko@gmail.com
