language: node_js
node_js:
  - 4
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm link ../create-elm-app

script: npm test

notifications:
  email:
    - duardeco@gmail.com
